export const GET_COMPLAINTS_COUNT = 'GET_COMPLAINTS_COUNT';
export const SHOW_COMPLAINTS_COUNT = 'SHOW_COMPLAINTS_COUNT';
export const GET_ALL_COMPLAINTS = 'GET_ALL_COMPLAINTS';
export const SHOW_ALL_COMPLAINTS = 'SHOW_ALL_COMPLAINTS';
export const GET_SINGLE_COMPLAINT = 'GET_SINGLE_COMPLAINT';
export const SHOW_SINGLE_COMPLAINT = 'SHOW_SINGLE_COMPLAINT';
export const ADD_NEW_COMPLAINT = 'ADD_NEW_COMPLAINT';
export const RESOLVE_COMPLAINT = 'RESOLVE_COMPLAINT';


