export const GET_ALL_ITEMS = 'GET_ALL_ITEMS';
export const SHOW_ALL_ITEMS = 'SHOW_ALL_ITEMS';
export const GET_SINGLE_ITEM = 'GET_SINGLE_ITEM';
export const SHOW_SINGLE_ITEM ='SHOW_SINGLE_ITEM';
export const ADD_NEW_ITEM ='ADD_NEW_ITEM'; 
export const EDIT_ITEM ='EDIT_ITEM'; 
export const DELETE_ITEM ='DELETE_ITEM'; 
export const GET_COUNT_ITEM = 'GET_COUNT_ITEM';
export const SHOW_COUNT_ITEM = 'SHOW_COUNT_ITEM';