export const ADD_NEW_REQUEST = 'ADD_NEW_REQUEST';
export const GET_ALL_REQUESTS = 'GET_ALL_REQUESTS';
export const SHOW_ALL_REQUESTS = 'SHOW_ALL_REQUESTS';
export const GET_SINGLE_REQUEST = 'GET_SINGLE_REQUEST';
export const SHOW_SINGLE_REQUEST = 'SHOW_SINGLE_REQUEST';
export const EDIT_REQUEST = 'EDIT_REQUEST';
export const EDIT_RETURN = 'EDIT_RETURN';

