export const ADD_NEW_VENDOR = 'ADD_NEW_VENDOR';
export const SHOW_ALL_VENDORS = 'SHOW_ALL_VENDORS';
export const GET_ALL_VENDORS = 'GET_ALL_VENDORS';
export const GET_SINGLE_VENDOR = 'GET_SINGLE_VENDOR';
export const SHOW_SINGLE_VENDOR = 'SHOW_SINGLE_VENDOR';
export const GET_COUNT_VENDORS = 'GET_COUNT_VENDORS';
export const SHOW_COUNT_VENDORS = 'SHOW_COUNT_VENDORS';
export const EDIT_VENDOR = 'EDIT_VENDOR';